<template>
  <div id="loading">
    <div class="loading-container">
      <img src="/static/logo.png" id="loading-image" alt width="200" height="200">
      <div class="loading-text" v-if="!errorMessage">Please wait as Uier loads...</div>
      <div
        class="error-text"
        v-if="errorMessage"
      >Could not connect to server. Trying again in fifteen seconds. You can also reload this page to try again.</div>
      <div class="text-muted" v-if="errorMessage">{{errorMessage}}</div>
    </div>
  </div>
</template>

<script>
export default {
  name: "Loading",
  data() {
    return {
      errorMessage: null
    };
  },
  mounted() {
    this.checkIfAuthenticated();
  },
  methods: {
    checkIfAuthenticated() {
      // Check if already authenticated
      var parent = this;
      fetch("http://localhost:8081/authenticated", {
        credentials: "include",
        method: "POST",
        headers: new Headers({
          "Content-Type": "application/json"
        })
      })
        .then(function(response) {
          return response.json();
        })
        .then(function(json) {
          if (json.status == "authenticated") {
            parent.$root.$data.user = json.user;
            parent.$root.$data.roles = json.roles;
            parent.$root.$data.isAuthenticated = true;
          } else {
            parent.$root.$data.isAuthenticated = false;
          }
        })
        .catch(function(error) {
          parent.errorMessage = error.message;
          window.setTimeout(function() {
            parent.checkIfAuthenticated();
          }, 15000);
        });
    }
  }
};
</script>

<style>
#loading {
  text-align: center;
  width: 100%;
  height: 100%;
}

#loading {
  display: -ms-flexbox;
  display: flex;
  -ms-flex-align: center;
  align-items: center;
  padding-top: 40px;
  padding-bottom: 40px;
  background-color: #f5f5f5;
}

body {
  display: -ms-flexbox;
  display: flex;
}

.loading-container {
  width: 100%;
  max-width: 330px;
  padding: 15px;
  margin: auto;
}
.loading-text {
  padding-top: 40px;
  font-weight: 400;
  font-size: 16px;
}
#loading-image {
  -webkit-animation: wobble-hor-bottom 1.4s 2s infinite both;
  animation: wobble-hor-bottom 1.4s 2s infinite both;
}
.error-text {
  padding-top: 40px;
  font-weight: 400;
  font-size: 16px;
  color: red;
}

/* ----------------------------------------------
 * Generated by Animista on 2019-6-22 20:44:22
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation wobble-hor-bottom
 * ----------------------------------------
 */
@-webkit-keyframes wobble-hor-bottom {
  0%,
  100% {
    -webkit-transform: translateX(0%);
    transform: translateX(0%);
    -webkit-transform-origin: 50% 50%;
    transform-origin: 50% 50%;
  }
  15% {
    -webkit-transform: translateX(-30px) rotate(-6deg);
    transform: translateX(-30px) rotate(-6deg);
  }
  30% {
    -webkit-transform: translateX(15px) rotate(6deg);
    transform: translateX(15px) rotate(6deg);
  }
  45% {
    -webkit-transform: translateX(-15px) rotate(-3.6deg);
    transform: translateX(-15px) rotate(-3.6deg);
  }
  60% {
    -webkit-transform: translateX(9px) rotate(2.4deg);
    transform: translateX(9px) rotate(2.4deg);
  }
  75% {
    -webkit-transform: translateX(-6px) rotate(-1.2deg);
    transform: translateX(-6px) rotate(-1.2deg);
  }
}
@keyframes wobble-hor-bottom {
  0%,
  100% {
    -webkit-transform: translateX(0%);
    transform: translateX(0%);
    -webkit-transform-origin: 50% 50%;
    transform-origin: 50% 50%;
  }
  15% {
    -webkit-transform: translateX(-30px) rotate(-6deg);
    transform: translateX(-30px) rotate(-6deg);
  }
  30% {
    -webkit-transform: translateX(15px) rotate(6deg);
    transform: translateX(15px) rotate(6deg);
  }
  45% {
    -webkit-transform: translateX(-15px) rotate(-3.6deg);
    transform: translateX(-15px) rotate(-3.6deg);
  }
  60% {
    -webkit-transform: translateX(9px) rotate(2.4deg);
    transform: translateX(9px) rotate(2.4deg);
  }
  75% {
    -webkit-transform: translateX(-6px) rotate(-1.2deg);
    transform: translateX(-6px) rotate(-1.2deg);
  }
}
</style>
